global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node-exporter
    static_configs:
      - targets:
          - homelab-server.home.arpa:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: caddy
    metrics_path: /metrics
    static_configs:
      - targets:
          - caddy:2019

  - job_name: fritz-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - fritz-exporter:9787

  - job_name: technitium-exporter
    scrape_interval: 30s
    static_configs:
      - targets:
          - technitium-exporter:9105
