---
- Infrastructure:
    - Homepage:
        href: https://homepage.home.arpa
        description: HomeLab landing page
        icon: homepage.png
    - DNS:
        href: https://dns.home.arpa
        description: Technitium DNS Server
        icon: technitium.png
        widget:
          type: technitium
          url: http://technitium:5380
          key: "{{HOMEPAGE_VAR_TECHNITIUM_API_KEY}}"
          range: LastDay
          fields:
            - totalQueries
            - totalServerFailure
            - totalBlocked
            - totalCached
    - Router:
        href: http://router.home.arpa
        description: FritzBox router
        icon: fritzbox.png
    - OpenSpeedTest:
        href: https://speedtest.home.arpa
        description: LAN speed testing
        icon: openspeedtest.png
    - Glances:
        href: https://glances.home.arpa
        description: Live host monitoring
        icon: glances.png
    - Uptime Kuma:
        href: https://status.home.arpa
        description: HomeLab availability monitoring
        icon: uptime-kuma.png
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: "{{HOMEPAGE_VAR_UPTIME_KUMA_STATUS_SLUG}}"
